name: setup-nix

runs:
  using: composite
  steps:
    - name: reclaim space (linux)
      if: runner.os == 'Linux'
      uses: wimpysworld/nothing-but-nix@main
      with:
        hatchet-protocol: rampage

    - name: install nix
      uses: cachix/install-nix-action@v31
      with:
        extra_nix_config: |
          build-dir = /nix/build
          fallback = true
          http-connections = 128
          max-substitution-jobs = 128
          substituters = https://nix-community.cachix.org
          trusted-public-keys = nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs=
          ${{ matrix.system == 'aarch64-linux' && 'extra-sandbox-paths = /sys/devices/system/cpu=/sys/devices/system/cpu /proc/cpuinfo=/proc/cpuinfo' || '' }}
    - name: create build-dir
      shell: bash
      run: sudo mkdir -p /nix/build
