name: CI
permissions:
  contents: read
  id-token: write
on:
  pull_request:
  push:
    branches: [main]
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        system:
          - x86_64-linux
          - aarch64-linux
    runs-on: >-
      ${{ (matrix.system == 'x86_64-linux' && 'ubuntu-latest') || (matrix.system == 'aarch64-linux' && 'ubuntu-24.04-arm') }}
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: .github/actions
      - name: setup nix
        uses: ./.github/actions/setup-nix
      - name: clone repo
        uses: actions/checkout@v4
      - name: nix build
        run: nix build --keep-going -L --system ${{ matrix.system }} .\#allPkgsEnv
